name: Prueba de ejecucion de un java github actions

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clona el repositorio
      uses: actions/checkout@v5
      
    - name: Usar java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Compilar archivo
      run:
        javac src/Hola.java
    - name: Ejecutar el archivo
      run:
        java -cp src Hola 